<a href="https://colab.research.google.com/github/Pham-Canh-An-Tien/data-mining/blob/main/bayesian_text_clasifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [8]:
! pip install kaggle
from google.colab import files
# Select the kaggle.json file
files.upload()
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json
! kaggle datasets download gaveshjain/ford-sentence-classifiaction-dataset
! unzip ford-sentence-classifiaction-dataset.zip

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (6.1.2)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.64.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2022.9.24)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)

Saving kaggle.json to kaggle.json
mkdir: cannot create directory ‘/root/.kaggle’: File exists
Downloading ford-sentence-classifiaction-dataset.zip to /content
 69% 2.00M/2.92M [00:01<00:00, 2.22MB/s]
100% 2.92M/2.92M [00:01<00:00, 2.63MB/s]
Archive:  ford-sentence-classifiaction-dataset.zip
  inflating: sample_submission.csv
  inflating: test_data.csv
  inflating: train_data.csv

In [13]:
train_dataset = pd.read_csv('train_data.csv')
test_dataset = pd.read_csv('test_data.csv')
display(train_dataset)

,Unnamed: 0,Sentence_id,New_Sentence,Type
0,0,GERRES15609,Author and/or Review architecture/design and o...,Responsibility
1,1,PHERES15784,Should be able to develop custom dynamic shape...,Responsibility
2,2,GERREQ10457,Experience in working crosslly with a larger ...,Requirement
3,3,GERSKL27235,"Previous business experience, including but no...",Skill
4,4,HONSSK18415,Delivering fast and right the first time.,SoftSkill
...,...,...,...,...
60110,60110,UAERES18030,"In this position, you will utilize your progr...",Responsibility
60111,60111,GERRES3026,"In addition, this individual will be responsib...",Responsibility
60112,60112,INDSSK5492,Good problem solving skills.,SoftSkill
60113,60113,PHESSK15092,Good Excel knowledge .,SoftSkill
60114,60114,HONEDU1643,"Bachelors Degree in Electrical Engineering, M...",Education

In [16]:
merged_dataset = pd.concat([train_dataset,test_dataset])
display(merged_dataset)

,Unnamed: 0,Sentence_id,New_Sentence,Type
0,0,GERRES15609,Author and/or Review architecture/design and o...,Responsibility
1,1,PHERES15784,Should be able to develop custom dynamic shape...,Responsibility
2,2,GERREQ10457,Experience in working crosslly with a larger ...,Requirement
3,3,GERSKL27235,"Previous business experience, including but no...",Skill
4,4,HONSSK18415,Delivering fast and right the first time.,SoftSkill
...,...,...,...,...
15024,15024,HONEXP17084,A minimum of 3 years of experience in Industri...,NaN
15025,15025,UAESSK45553,Track record of managing multiple projects wit...,NaN
15026,15026,GERSSK14317,"In addition, the candidate should have effecti...",NaN
15027,15027,PHEREQ4980,Candidate should have sufficient knowledge on ...,NaN
15028,15028,PHESKL2893,Experience in deployment and upgrading & imple...,NaN

In [18]:
train_ratio = 0.6
val_ratio = 0.2
test_ratio = 0.2
train_set,remain_set = train_test_split(merged_dataset, test_size = (val_ratio+test_ratio))
val_set,test_set = train_test_split(remain_set,test_size =test_ratio/(val_ratio+test_ratio))
display(train_set)
display(val_set)
display(test_set)

,Unnamed: 0,Sentence_id,New_Sentence,Type
42063,42063,UAESSK11903,Personal leadership qualities; the ability to ...,SoftSkill
46904,46904,COGSSK3295,A collaborative style with ability to interac...,SoftSkill
24323,24323,PHEREQ51281,"Exposure to warehouse management, trade compli...",Requirement
33518,33518,PHESSK11784,Regarded as an authority in Project Managemen...,SoftSkill
57029,57029,GEREXP30177,Minimum 5 years field equipment experience.,Experience
...,...,...,...,...
43155,43155,HONEDU2024,Bachelors degree is required.,Education
24850,24850,INDEXP44860,Minimum of 2 Years experience working with En...,Experience
25821,25821,COGREQ14718,Possess a broad range of knowledge in support ...,Requirement
36805,36805,UAEEDU2623,MBA Degree.,Education
11663,11663,INDSKL8605,Rich experienced in development & deployment ...,NaN

,Unnamed: 0,Sentence_id,New_Sentence,Type
14319,14319,GERRES37614,"Work from set-up sheets, prints, specification...",NaN
11472,11472,UAERES8691,Application programming and providing feedbac...,Responsibility
11232,11232,INDSSK15933,his is a dummy block of text And this is repre...,SoftSkill
46570,46570,COGSSK14831,Market Leadership.,SoftSkill
4163,4163,GEREXP4600,"4+ years of software coding, development, des...",NaN
...,...,...,...,...
24388,24388,UAESSK48663,Incident/Problem management.,SoftSkill
41949,41949,INDEXP31429,5+ years of experience in teams management.,Experience
45312,45312,HONEDU9053,"Bachelors degree in engineering, Computer Sci...",Education
45292,45292,GEREDU51208,"Bachelors Degree in Business Administration, ...",Education
28801,28801,COGREQ31722,Experience with business analytics and soluti...,Requirement

,Unnamed: 0,Sentence_id,New_Sentence,Type
7125,7125,INDEDU19299,Advanced Network / PC certification and Cyber...,Education
28734,28734,INDSKL44008,In-depth understanding of Microsoft 365 produ...,Skill
3409,3409,INDEXP2039,B.E/B.Tech or MBA in FiNonece/Program manageme...,Experience
24884,24884,INDRES15403,An effective leader with capabilities in leadi...,Responsibility
5695,5695,INDRES39348,Provide backup support for the Principal Sour...,NaN
...,...,...,...,...
48344,48344,COGRES16977,Coordinates material availability with custom...,Responsibility
17379,17379,HONRES19167,Confront problems directly and face adversity...,Responsibility
598,598,GERREQ45334,Willingness to learn new technologies.,NaN
43754,43754,COGREQ2575,Willingness to learn alternate technologies an...,Requirement
8854,8854,COGREQ34450,Familiar with mixed signal simulation and ana...,NaN